import { DataSource } from 'typeorm';
import {
  User,
  Profile,
  Request,
  RequestLocation,
  Category,
  Chat,
  Message,
  Payment,
  Rating,
  Tenant,
  LocationEntity,
  Address,
} from './src/database/entities';

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DATABASE_HOST || 'localhost',
  port: parseInt(process.env.DATABASE_PORT || '5432'),
  username: process.env.DATABASE_USERNAME || 'postgres',
  password: process.env.DATABASE_PASSWORD || 'postgres',
  database: process.env.DATABASE_NAME || 'app_db',
  synchronize: process.env.NODE_ENV === 'development',
  logging: process.env.NODE_ENV === 'development',
  entities: [
    User,
    Profile,
    Address,
    Request,
    RequestLocation,
    Category,
    LocationEntity,
    Chat,
    Message,
    Payment,
    Rating,
    Tenant,
  ],
  migrations: [__dirname + '/src/database/migrations/**/*{.ts,.js}'],
  subscribers: [],
});
